# Generated by Django 5.2.7 on 2025-10-28 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('extra_note', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('new_measurements_head', models.PositiveIntegerField(blank=True, null=True)),
                ('new_measurements_chest', models.PositiveIntegerField(blank=True, null=True)),
                ('new_measurements_waist', models.PositiveIntegerField(blank=True, null=True)),
                ('new_measurements_hips', models.PositiveIntegerField(blank=True, null=True)),
                ('new_measurements_sleeve', models.PositiveIntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.client')),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('head', models.PositiveIntegerField(blank=True, null=True)),
                ('chest', models.PositiveIntegerField(blank=True, null=True)),
                ('waist', models.PositiveIntegerField(blank=True, null=True)),
                ('hips', models.PositiveIntegerField(blank=True, null=True)),
                ('sleeve', models.PositiveIntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='users.client')),
            ],
        ),
    ]
