# Generated by Django 5.2.7 on 2025-11-04 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atelier', '0002_invoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
