# Generated by Django 5.2.7 on 2025-10-28 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CLIENT', 'Client'), ('SARTA', 'Sarta'), ('ADMIN', 'Admin')], default='CLIENT', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='F', max_length=1)),
                ('measurements_head', models.PositiveIntegerField(blank=True, null=True)),
                ('measurements_chest', models.PositiveIntegerField(blank=True, null=True)),
                ('measurements_waist', models.PositiveIntegerField(blank=True, null=True)),
                ('measurements_hips', models.PositiveIntegerField(blank=True, null=True)),
                ('measurements_sleeve', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
